# Generated by Django 3.2.18 on 2023-04-06 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
        ('gameconsole', '0002_auto_20230406_2327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0002_rename_title_tag_name'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_consoles_released_on',
            field=models.ManyToManyField(related_name='games_released_on_console', to='gameconsole.GameConsole'),
        ),
        migrations.AddField(
            model_name='game',
            name='players_that_own_game',
            field=models.ManyToManyField(related_name='games_owned_by_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher_of_game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_published', to='publisher.publisher'),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='tags_for_game',
            field=models.ManyToManyField(related_name='games_with_tag', to='tag.Tag'),
        ),
    ]
