# Generated by Django 3.2.18 on 2023-04-06 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consolemaker', '0001_initial'),
        ('gameconsole', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameconsole',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='gameconsole',
            name='maker_of_console',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consoles_from_brand', to='consolemaker.consolemaker'),
        ),
    ]
