# Generated by Django 3.2.18 on 2023-04-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameconsole', '0002_auto_20230406_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconsole',
            name='name_code',
            field=models.CharField(default='CODE', max_length=6),
        ),
    ]
