# Generated by Django 3.2.18 on 2023-04-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameconsole', '0003_gameconsole_name_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconsole',
            name='name_code',
            field=models.CharField(default='CODE', max_length=15),
        ),
    ]
